### ISSUE TITLE
Land has the wrong gender

### ISSUE THREAD

**Issue by sitamshrijal** [Andrew-2609/german-gender-api#1]
The noun _Land_  (state, country) has the gender masculine in the API. It should be neuter.

https://german-gender-api.deta.dev/api/v1/nouns/Land returns
```json
{
  "noun": "Land",
  "gender": "masculine"
}
```

**Comment by Andrew-2609** [comment]
Good evening, Sitamsh!

Thanks for opening this Issue. Unfortunately, it's been a while since the last time I worked on this project, and I'll probably not do it again :/ I'm studying other things at the moment, but feel free to use this code as you please!

**Comment by sitamshrijal** [comment]
Thanks, appreciate it! Closing issue.

**Comment by sitamshrijal** [comment]
Thanks, appreciate it! Closing issue.
